### ISSUE TITLE
Resume is not always pulled from bedetheque.com

### ISSUE THREAD

**Issue by CeskoFTB** [maforget/Bedetheque-Scrapper-2#10]
**Describe the bug**
Resume is not always pulled from bedetheque.com

**Link**
(https://www.bedetheque.com/BD-Morgue-pleine-431669.html)

**Comment by maforget** [comment]
This was an edge case, because there was no title (being a One Shot) and that the serie and book summary where the same. It was skipped.

Fixed in 46bfa4ca369ad5df9d8a08114626fbeb7fecdcc3
