### ISSUE TITLE
Question / Evolution ?

### ISSUE THREAD

**Issue by siddjellali** [maforget/Bedetheque-Scrapper-2#11]
Bonjour, 

Existe-t-il un moyen de sélectionner une issue spécifique (ex : INT 2012a) ?
https://www.bedetheque.com/BD-Batman-Annee-un-INT-Vengeance-Oblige-45144.html
Les informations relatif à l'éditeur ect sont différentes, sympa pour l'organisation des fichiers.

Merci

**Comment by maforget** [comment]
Existes déjà, désactivé l'options Éditions Automatiques. Un menu vous permettra de choisir l'édition voulu.
