### ISSUE TITLE
Scraper (Behavior)

### ISSUE THREAD

**Issue by siddjellali** [maforget/Bedetheque-Scrapper-2#12]
Bonjour, 

Je constate que je n'ai pas le même comportement quand j'utilise pas le même bouton (même fonctionnalité normalement).

**Exemple:**
https://www.bedetheque.com/BD-Batman-Dark-Knight-INT-Batman-Dark-Knight-Edition-integrale-11931.html

![image](https://user-images.githubusercontent.com/3965823/150672655-d8b059e9-4f16-46a8-a19e-39aa623665c4.png)
![image](https://user-images.githubusercontent.com/3965823/150672709-4c645154-0456-4c42-99b3-e5b2ba64840c.png)

Puis le clique sur Bédéthèque Scraper 2 et là j'obtiens une donnée en plus (Genre).
Bizarre non ?

![image](https://user-images.githubusercontent.com/3965823/150672773-3b61a0c0-48a8-4097-9fc5-98796b50b4fe.png)

Merci pour ton analyse.

**Comment by maforget** [comment]
C'est normal, le bouton rouge est le QuickScrapper quand vous sélectionner le lien directement. Le bouton aux bas est le scrapper normal (même fonction que le bouton blanc) que vous devriez utiliser normalement.

La fonction normal du scrapper est de lire la page de la série et ensuite celle du tome. Cet info ce retrouve dans la page de la série, donc quand vous utilisé le lien du tome vous sauté la page de série donc il manque cet info et tous autre info qui pourrait ci trouvé (ex: résumé de la série).

Vous pouvez toujours utilisé le scrapper normal après un QS pour rajouter cet information.

**Comment by siddjellali** [comment]
Excellent merci !
