### ISSUE TITLE
Interface pour ligne de commande ?

### ISSUE THREAD

**Issue by Spiralo-Idioide** [maforget/Bedetheque-Scrapper-2#17]
Bonjour !

Avant tout merci beaucoup pour cet outil qui m'a toujours été extrêmement pratique. 

Je suis en train de migrer entièrement de ComicRack à un mélange entre Calibre et des Scripts persos mais une fois que j'aurai fini je n'aurai plus d'accès aux données de bedetheque.
Je me demandai donc si il était envisageable de faire une version de l'outil accessible simplement en ligne de commande en plus de la version sous forme d'addon. 

Et merci encore pour l'outil !

**Comment by maforget** [comment]
Non, honnêtement ce script est un calvaire déjà. Je ne suis même plus capable de le debugger avec Visual Studio. Je vais régler des bugs et des choses simples seulement que je peux faire facilement.

Je doute beaucoup de la pertinence de passé de Calibre à ComicRack pour les BD. Ca te prendrais surtout un plugin pour Calibre pour importer les métadonnées de bédéthèque ou d'importer des ComicInfo.xml. As ce point tu es probablement mieux d'utiliser d'autre programme (comme Komga) qui supporte déjà les fichier ComicInfo.xml pour que les données de ComicRack puissent être réutiliser. Avec tous ca pourquoi ne pas rester avec ComicRack, qui fonctionne encore bien.

Aussi il y a déjà d'autre scrapper pour Bedetheque indépendant. 
Un que j'ai vu partager -> https://github.com/lbesnard/bdnex
