### ISSUE TITLE
Scrapper retourne le nombre de planches au lieu de l'ISBN dans certains cas

### ISSUE THREAD

**Issue by paprickka** [maforget/Bedetheque-Scrapper-2#4]
Dans certains cas, le scrapper renseigne le champ ISBN avec le nombre de planches plutôt que l'ISBN lui-même.

**Comment by maforget** [comment]
Aurais-tu un lien ou cette situation est présente?

**Comment by paprickka** [comment]
![image](https://user-images.githubusercontent.com/83698969/117202598-49fbea00-adee-11eb-981b-f60daed72ba3.png)

Dans le cas de cette série ( La dernière prophétie), pour les tomes 1 et 2 c'est le nombre de planches qui est retourné alors que pour les tomes 3 à 5 c'est bien l'ISBN.
