### ISSUE TITLE
Add year?

### ISSUE THREAD

**Issue by Bonaf1de** [maforget/Bedetheque-Scrapper-2#5]
Thanks for you awesome work; the scraper really saves me much time adding metadata!

Question: **is is possible to add the year of publishment?** At this time I have to manually add the years.

**Comment by maforget** [comment]
The year and month are already set, check your settings to make sure that Dep. Legal (Leg. Deposit) is activated. 

Check the gif I made the other day. the year and month are being added.
https://user-images.githubusercontent.com/11904426/115951797-b56dbf80-a4b0-11eb-821b-6e97ca2cfca1.gif

**Comment by Bonaf1de** [comment]
Wowwww, cheers!
