### ISSUE TITLE
Title mot set when it's the same as the series name

### ISSUE THREAD

**Issue by vanch3d** [maforget/Bedetheque-Scrapper-2#7]
This is happening for both "one shot" records as well as full series but with the title of the book exactly the same as the serie.
For example:
- https://www.bedetheque.com/BD-Oiseaux-416930.html, scrapes `Oiseaux (Les)` for `series` (with appropriate article handling but `title` is empty
- https://www.bedetheque.com/BD-Blue-Note-INT-Blue-note-292282.html, scrapes `Blue Note` for `series`, `INT` for `number` but again `title` is empty

Note that I would expect the article processing NOT to happen for the title, meaning it will scrapes `Oiseaux (Les)` for `series` and `Les oiseaux` for `title`.

**Comment by maforget** [comment]
This is intended, having `Les Oiseaux - Les Oiseaux` seemed redundant, especially for one shots. So whenever the series name and title are the same the title is blanked.

You can delete these lines to remove this effect.
https://github.com/maforget/Bedetheque-Scrapper-2/blob/da058a7206e6ce974175f23d304a25e05c6dc031/src/BedethequeScraper2.py#L1049-L1050
