### ISSUE TITLE
Unable to scrap this comics

### ISSUE THREAD

**Issue by siddjellali** [maforget/Bedetheque-Scrapper-2#9]
Hello thanks for the amazing job your done.
Please find below some issue i have with this title.
https://www.bedetheque.com/BD-Deadpool-Marvel-France-7e-serie-2020-Tome-1-La-Guerre-des-royaumes-383212.html

**Comment by maforget** [comment]
Je ne suis pas certain quel problème vous avez, mais ce volume peut être scrapper. Si le nom de la série est Deadpool seulement, le scrapper va prendre la série `Deadpool` dans cette liste https://www.bedetheque.com/bandes_dessinees_D.html.

Si vous changer le nom de la série pour quelle soit `Deadpool (` (pour ne pas correspondre exactement à Deadpool), vous allez pouvoir scrapper ce volume. Un menu va s'ouvrir et vous laissez le choix de choisir quelle série. En cas de problème il y a toujours le Quick Scrape qui permet de mettre un lien direct.

Par contre j'ai découvert que dans la liste https://www.bedetheque.com/bandes_dessinees_D.html après `Deadpool (Marvel France 7e série - 2020)` il y a un espace qui fait que même si vous avez le nom exact le menu s'ouvre pour demander de choisir quelle série au lieu de choisir automatiquement la bonne série. Je ne sais pas si ceci est le problème que vous aviez.

Voir 6c8be8a868740da2157aa67800295c92863b87b8 pour une mise à jour dû à l'espace qui ne devrait pas être la et fait que le menu s'ouvre au lieu de choisir automatiquement la série.

**Comment by siddjellali** [comment]
Cool merci mais sauf erreur, il manque des information (Format, Editeur, Impression)

![image](https://user-images.githubusercontent.com/3965823/149992090-992fc6ec-5caa-4e18-9da4-6951434264f6.png)

**Comment by maforget** [comment]
Vérifier vos paramètres pour les champs que vous voulez voir. Pour le champ Impression il s’agit de Collection et dans ce cas, ci n'existe pas sur la page, donc on ne peux aller chercher de l'information qui n’existe pas. Aussi pour le format (Taille) il y a une option pour remplacer Taille par OneShot que vous voulez désactivé, car ça désactive le champs Taille (Format) automatiquement.

Mais à regarder votre image il vous manque beaucoup d'autre d'information je doute que vous n'ayez même pas scrapper, juste le champ langue devrait être mis automatiquement à Francais. Comme j'ai mentionné scrapper Deadpool ne vous donneras pas la bonne série, car celle-ci ce nomme `Deadpool (Marvel France 7e série - 2020)` et qu'une série `Deadpool` existe également, vous devez changé le nom avant de scrapper.

Voici que cette fenêtre doit avoir l'air lorsque toutes les information on été scrapper.
![Screenshot 2022-01-19 143924](https://user-images.githubusercontent.com/11904426/150203470-b0ce2d55-3103-4957-8dbb-151993e763ee.jpg)

Je suggère d'ouvrir ComicRack avec l'option `-ssc` à la fin du chemin dans votre raccourcis pour ouvrir la fenêtre Script Output et copier ici ce qui est inscrit sous `Begin!`

Comme ceci:
```
=========================- Begin! -=========================

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Nom Série = Deadpool (Marvel France 7e série - 2020)	No = [1]
Recherche sur le Web avec Nom de Série: Deadpool (Marvel France 7e série - 2020)
URL Série: https://www.bedetheque.com/serie-68222-BD-Deadpool-Marvel-France-7e-serie-2020.html
Recherche sur le Web avec No. d'Album [ 1] 
============================================================
parseSerieInfo a) https://www.bedetheque.com/serie-68222-bd-deadpool-marvel-france-7e-serie-2020__10000.html b) False
============================================================
Genre:  Super-héros
** Résumé Serie non trouvé !
Série En cours
Langue:  Fr
Val. Proposée No
Nbr. d'item dans la Liste Album est de: 1
---> Seulement 1 item dans la liste
** URL de l'Album dans la Série:  https://www.bedetheque.com/BD-Deadpool-Marvel-France-7e-serie-2020-Tome-1-La-Guerre-des-royaumes-383212.html
============================================================
parseAlbumInfo a) https://www.bedetheque.com/BD-Deadpool-Marvel-France-7e-serie-2020-Tome-1-La-Guerre-des-royaumes-383212.html b) 1 c) False
============================================================
Tome) 1 Alt)  Title) La Guerre des royaumes
---> Seulement 1 item dans la liste
Choisi #Alt:  // Titre: La Guerre des royaumes
** URL de l'Album:  https://www.bedetheque.com/BD-Deadpool-Marvel-France-7e-serie-2020-Tome-1-La-Guerre-des-royaumes-383212.html
Num:  1
Alt:  
Nom Série = Deadpool (Marvel France 7e série - 2020)
Titre:  La Guerre des royaumes
Scenariste(s):  Christ Yost, Christopher Hastings, Daniel Kibblesmith
Dessinateur(s):  George Klein, Salva Espín, Ricardo Lopez Ortiz
Coloriste(s):  George Klein, Matt Yackey, Felipe Sobreiro 
Couverturiste:  Nic Klein 
Dèpot lègal:  1/2020
Editeur:  Panini Comics
ISBN:  978-2-8094-8344-4
Lettrage:  Christophe Semal
Collection:  
Taille:  Format comics
Résumé Album trouvé !
Info édition:  trouvé !
Nom Série =  Deadpool (Marvel France 7e série - 2020)
Couverture trouvée:  https://www.bedetheque.com/media/Couvertures/Couv_383212.jpg
N. de Planches:  112
# Temps nécessaire:  0:00:02

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Temps nécessaire pour le Scrape Total:  0:00:02
=========================- End! -=========================
```

**Comment by siddjellali** [comment]
Merci, j'apprécie le retour complète.
Un autre élement bizarre que je constate.

Quand je scrap le comics en direct, j'obtiens ceci. 
![image](https://user-images.githubusercontent.com/3965823/150413684-1a6d14b4-0197-4a03-a74f-2bede4e2db84.png)

Par contre si je scrap la série et que je choisi l'issue, j'obtiens ceci, est-ce que c'est normal pour vous ?

![image](https://user-images.githubusercontent.com/3965823/150413783-02412734-cb7f-4472-8290-a572790663d9.png)

Avec l'option -scc j'ai bien le output qui sort mais pas de begin.

![image](https://user-images.githubusercontent.com/3965823/150413974-c44fb3d5-7446-4c59-a7af-c7c749bdfbc5.png)

**Comment by maforget** [comment]
Il faut activer l'option de Debug Interne, pour voir le détail, désolé de l'oublie.

Mais effectivement ce n’est ce qui est attendu, le comic n'est tous juste pas scrapper. Le problème venait du fait qu'il a le mot série dans le titre, ce qui faisait que le scrapper pensait que le lien était pour la page de série et non la page du tome. Corriger dans le commit abdfa165a5cecfbf7e55286aa4b5fb6890d180ed

**Comment by siddjellali** [comment]
Ah excellent merci !
Vous ne publiez pas de nouvelle release avec le correctif ?
Bon weekend et merci !

**Comment by maforget** [comment]
Eventuellement

**Comment by siddjellali** [comment]
Merci :)
